on:
  push:


jobs:
  set_matrix:
    name: set matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: matrix
        name: set matrix
        run: |
          cd monorepo 
          echo -n "::set-output name=servit ce::["; ls -1d */ | tr -d '/' | awk -v ORS=', ' '{print "\""$0"\""}' | sed 's/,\s$/]/'

    outputs:
      service: ${{ steps.matrix.outputs.service }}

  buf:
    needs: [set_matrix]
    name: breaking check and lint 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJson(needs.set_matrix.outputs.service) }}
    steps:
      - uses: actions/checkout@v2
      - name: setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.GITHUB_TOKEN }}
      - name: buf lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: monorepo/${{ matrix.service }}
      - name: check branking chnages
        uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/RcAvenger/repo.git#branch=main'
