on:
  push:
    branches:
      - main

jobs:
  dispatch:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: peter-evans/repository-dispatch@v2
        with:
          repository: "RcAvenger/repo-go-test"
          token: ${{ secrets.PAT }}
          event-type: create-pull-request
          client-payload: '{"ref", "${{ github.ref }}"}'
