on:
  issue_comment:
    types:
      - created

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.GITHUB_TOKEN }}
      - name: format
        run: buf format -w
      - name: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Code Formatter Change
          ref: ${{ github.head_ref }}
